ALTER TABLE communes
ADD COLUMN IF NOT EXISTS insee_code VARCHAR(5);

ALTER TABLE communes
ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;

ALTER TABLE communes
ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
