ALTER TABLE partners
ADD COLUMN IF NOT EXISTS postal_code VARCHAR(10);

ALTER TABLE partners
ADD COLUMN IF NOT EXISTS city VARCHAR(128);

ALTER TABLE partners
ADD COLUMN IF NOT EXISTS email VARCHAR(255);
