ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS opt_in_email BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS opt_in_sms BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS opt_in_email_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS opt_in_sms_at TIMESTAMPTZ;
